<?php
    function groceries_menu () {
        $items = array();
        $groc_names = array('grocery_list', 'another_list', 'yet_another');

        foreach ($groc_names as $groc_name) {
            $items[$groc_name] = array(
                'title' => $groc_name,
                'page callback' => 'get_list',
                'access callback' => TRUE,
                'type' => MENU_NORMAL_ITEM,
            );
        }
        return $items;
    }

    function get_list() {
        $groceries = array('eggs' => array('price' => 2.99, 'quantity' => 1), 'hamburger' => array('price' => 5.99, 'quantity' => 4));
        $grocery_output = '<p>Your Grocery List:</p><ul>';
        $bill_total = 0;
        foreach($groceries as $key => $value) {
            $grocery_output .= '<li>' . $key . ' price: $' . $value["price"] . ' quantity: ' . $value["quantity"] . 'total = $' . $value["price"] * $value["quantity"] . '</li>';
            $bill_total += $value["price"] * $value["quantity"];
        };
        $grocery_output .= '</ul>';
        $grocery_output .= '<h2> Your total bill will be $' . $bill_total;

        return $grocery_output;
    }
